### PR TITLE
refactor(CH): make time type generic

### PR DESCRIPTION
**Pull request by 0xangelo**
Also removes a TODO (see 75bfc59 for details)

### CODE REVIEW

**Comment by nickkuk** [comment]
Did you try to use `frame_support::traits::Time` instead of `frame_support::traits::UnixTime`? It seems to be more straightforward.

Also do you need `rem_euclid`? It seems that you use this method for strictly positive arguments. In this case it is the same as `rem`, so you also don't need `divrem` crate, `std::ops::Rem` should be enough.

**Review by Cardosaum — APPROVED** [review]
LGTM!

**Comment by 0xangelo** [comment]
> Did you try to use `frame_support::traits::Time` instead of `frame_support::traits::UnixTime`? It seems to be more straightforward.

I looked into it but decided to use `frame_support::traits::UnixTime` since Angular uses it too.

> Also do you need `rem_euclid`? It seems that you use this method for strictly positive arguments. In this case it is the same as `rem`, so you also don't need `divrem` crate, `std::ops::Rem` should be enough.

I'll look into that and remove the dependency on `divrem` if possible

**Comment by 0xangelo** [comment]
@nickkuk I removed the dependency on `divrem`, thanks!

**Review by nickkuk — APPROVED** [review]

**Pull request merged**
